name: caiman
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.1.0=pyhd8ed1ab_0
  - aiohappyeyeballs=2.4.3=pyhd8ed1ab_0
  - aiohttp=3.11.4=py311h4921393_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alabaster=1.0.0=pyhd8ed1ab_0
  - anyio=4.6.2.post1=pyhd8ed1ab_0
  - aom=3.7.1=h463b476_0
  - applaunchservices=0.3.0=pyh534df25_3
  - appnope=0.1.4=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311h460d6c5_5
  - arrow=1.3.0=pyhd8ed1ab_0
  - asciitree=0.3.3=py_2
  - astroid=3.3.5=py311h267d04e_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_2
  - async-lru=2.0.4=pyhd8ed1ab_0
  - asyncssh=2.18.0=pyhd8ed1ab_0
  - atomicwrites=1.4.1=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - autopep8=2.0.4=pyhd8ed1ab_0
  - av=12.3.0=py311hb179bab_0
  - babel=2.16.0=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_4
  - backports.tarfile=1.2.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - binaryornot=0.4.4=py_1
  - black=24.10.0=py311h267d04e_0
  - bleach=6.2.0=pyhd8ed1ab_0
  - blinker=1.9.0=pyhff2d567_0
  - bokeh=3.6.1=pyhd8ed1ab_0
  - brotli=1.1.0=hd74edd7_2
  - brotli-bin=1.1.0=hd74edd7_2
  - brotli-python=1.1.0=py311h3f08180_2
  - bzip2=1.0.8=h99b78c6_7
  - c-ares=1.34.3=h5505292_0
  - ca-certificates=2024.12.14=hf0a4a13_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.5.0=pyhd8ed1ab_0
  - caiman=1.11.3=py311hb9542d7_0
  - cairo=1.18.0=hc6c324b_2
  - certifi=2024.12.14=pyhd8ed1ab_0
  - cffi=1.17.1=py311h3a79f62_0
  - chardet=5.2.0=py311h267d04e_2
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=3.1.0=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorcet=3.1.0=pyhd8ed1ab_0
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.3.1=py311h210dab8_0
  - cookiecutter=2.6.0=pyhca7485f_0
  - cryptography=43.0.3=py311h544b224_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - cytoolz=1.0.0=py311h460d6c5_1
  - dask-core=2024.11.2=pyhff2d567_1
  - dav1d=1.2.1=hb547adb_0
  - debugpy=1.8.8=py311h155a34a_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.15=pyhff2d567_0
  - diff-match-patch=20241021=pyhd8ed1ab_0
  - dill=0.3.9=pyhd8ed1ab_0
  - docstring-to-markdown=0.15=pyhd8ed1ab_0
  - docutils=0.21.2=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - fasteners=0.17.3=pyhd8ed1ab_0
  - ffmpeg=6.1.1=gpl_ha63e52a_101
  - flake8=7.1.1=pyhd8ed1ab_0
  - flatbuffers=23.5.26=h13dd4ca_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.55.0=py311h4921393_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=hadb7bae_2
  - fribidi=1.0.10=h27ca646_0
  - frozenlist=1.5.0=py311hae2e1ce_0
  - fsspec=2024.10.0=pyhff2d567_0
  - fzf=0.56.3=h145549b_0
  - gast=0.5.5=pyhd8ed1ab_0
  - gettext=0.22.5=h8414b35_3
  - gettext-tools=0.22.5=h8414b35_3
  - giflib=5.2.2=h93a5062_0
  - glib=2.82.2=hb1db9eb_0
  - glib-tools=2.82.2=h25d4a46_0
  - gmp=6.3.0=h7bae524_2
  - gnutls=3.7.9=hd26332c_0
  - google-auth=2.36.0=pyhff2d567_0
  - google-auth-oauthlib=1.2.1=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyhd8ed1ab_1
  - graphite2=1.3.13=hebf3989_1003
  - grpcio=1.59.3=py311hf5d242d_0
  - gst-plugins-base=1.24.7=hb49d354_0
  - gstreamer=1.24.7=hc3f5269_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - h5py=3.12.1=nompi_py311h0fa3d65_102
  - harfbuzz=8.5.0=h1836168_0
  - hdf5=1.14.3=nompi_hec07895_105
  - hdmf=3.14.5=pyh2e8e312_0
  - holoviews=1.20.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.27.2=pyhd8ed1ab_0
  - humanfriendly=10.0=pyh707e725_8
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=73.2=hc8870d7_0
  - idna=3.10=pyhd8ed1ab_0
  - imagecodecs-lite=2019.12.3=py311h5d790af_8
  - imageio=2.36.0=pyh12aca89_1
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_metadata=8.5.0=hd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - inflection=0.5.1=pyh9f0ad1d_0
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - ipykernel=6.29.5=pyh57ce528_0
  - ipyparallel=9.0.0=pyhff2d567_0
  - ipython=8.29.0=pyh707e725_0
  - ipywidgets=8.1.5=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - isort=5.13.2=pyhd8ed1ab_0
  - jaraco.classes=3.4.0=pyhd8ed1ab_1
  - jaraco.context=5.3.0=pyhd8ed1ab_1
  - jaraco.functools=4.0.0=pyhd8ed1ab_0
  - jasper=4.2.4=h6c4e4ef_0
  - jedi=0.19.2=pyhff2d567_0
  - jellyfish=1.1.0=py311h481aa64_1
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - json5=0.9.28=pyhff2d567_0
  - jsonpointer=3.0.0=py311h267d04e_1
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_0
  - jupyter=1.1.1=pyhd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_bokeh=4.0.5=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.2.6=pyhff2d567_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.3=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_0
  - keras=2.15.0=pyhd8ed1ab_0
  - keyring=25.5.0=pyh534df25_0
  - kiwisolver=1.4.7=py311h2c37856_0
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lazy-loader=0.4=pyhd8ed1ab_1
  - lazy_loader=0.4=pyhd8ed1ab_1
  - lcms2=2.16=ha0e7c42_0
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20230802.1=cxx17_h13dd4ca_0
  - libaec=1.1.3=hebf3989_0
  - libasprintf=0.22.5=h8414b35_3
  - libasprintf-devel=0.22.5=h8414b35_3
  - libass=0.17.1=hf7da4fe_1
  - libblas=3.9.0=25_osxarm64_openblas
  - libbrotlicommon=1.1.0=hd74edd7_2
  - libbrotlidec=1.1.0=hd74edd7_2
  - libbrotlienc=1.1.0=hd74edd7_2
  - libcblas=3.9.0=25_osxarm64_openblas
  - libclang-cpp15=15.0.7=default_he012953_5
  - libclang13=19.1.2=default_h5f28f6d_1
  - libcurl=8.10.1=h13a7ad3_0
  - libcxx=19.1.3=ha82da77_0
  - libdeflate=1.22=hd74edd7_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h93a5062_2
  - libexpat=2.6.4=h286801f_0
  - libffi=3.4.2=h3422bc3_5
  - libgettextpo=0.22.5=h8414b35_3
  - libgettextpo-devel=0.22.5=h8414b35_3
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - libglib=2.82.2=h07bd6cf_0
  - libgrpc=1.59.3=h9560976_0
  - libhwloc=2.11.2=default_h3f80f97_1000
  - libiconv=1.17=h0d3ecfb_2
  - libidn2=2.3.7=h93a5062_0
  - libintl=0.22.5=h8414b35_3
  - libintl-devel=0.22.5=h8414b35_3
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=25_osxarm64_openblas
  - liblapacke=3.9.0=25_osxarm64_openblas
  - libllvm15=15.0.7=h2621b3d_4
  - libllvm19=19.1.2=haf57ff0_0
  - libnghttp2=1.64.0=h6d7220d_0
  - libogg=1.3.5=h99b78c6_0
  - libopenblas=0.3.28=openmp_hf332438_1
  - libopencv=4.9.0=py311h22734c1_5
  - libopenvino=2023.2.0=he6dadac_4
  - libopenvino-arm-cpu-plugin=2023.2.0=he6dadac_4
  - libopenvino-auto-batch-plugin=2023.2.0=hc9f00d9_4
  - libopenvino-auto-plugin=2023.2.0=hc9f00d9_4
  - libopenvino-hetero-plugin=2023.2.0=hf483cef_4
  - libopenvino-ir-frontend=2023.2.0=hf483cef_4
  - libopenvino-onnx-frontend=2023.2.0=h7939876_4
  - libopenvino-paddle-frontend=2023.2.0=h7939876_4
  - libopenvino-pytorch-frontend=2023.2.0=hebf3989_4
  - libopenvino-tensorflow-frontend=2023.2.0=he0d35a2_4
  - libopenvino-tensorflow-lite-frontend=2023.2.0=hebf3989_4
  - libopus=1.3.1=h27ca646_1
  - libpng=1.6.44=hc14010f_0
  - libpq=16.5=h0224a88_0
  - libprotobuf=4.24.4=h810fc01_0
  - libre2-11=2023.09.01=h741fcf5_1
  - libsodium=1.0.20=h99b78c6_0
  - libspatialindex=2.0.0=h00cdb27_0
  - libsqlite=3.47.0=hbaaea75_1
  - libssh2=1.11.0=h7a5bd25_0
  - libtasn1=4.19.0=h1a8c8d9_0
  - libtiff=4.7.0=hfce79cd_1
  - libunistring=0.9.10=h3422bc3_0
  - libvorbis=1.3.7=h9f76cd9_0
  - libvpx=1.13.1=hb765f3a_0
  - libwebp=1.4.0=h54798ee_0
  - libwebp-base=1.4.0=h93a5062_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.12.7=h9a80f22_3
  - libzlib=1.3.1=h8359307_2
  - linkify-it-py=2.0.3=pyhd8ed1ab_0
  - llvm-openmp=19.1.3=hb52a8e5_0
  - locket=1.0.0=pyhd8ed1ab_0
  - markdown=3.6=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.2=py311h56c23cb_0
  - matplotlib=3.9.2=py311ha1ab1f8_2
  - matplotlib-base=3.9.2=py311hbe3227e_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd8ed1ab_0
  - mdit-py-plugins=0.4.2=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - ml_dtypes=0.2.0=py311h9e438b8_2
  - more-itertools=10.5.0=pyhd8ed1ab_0
  - msgpack-python=1.1.0=py311h2c37856_0
  - multidict=6.1.0=py311h30e7462_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy=1.13.0=py311hae2e1ce_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - mysql-common=8.3.0=h1687695_5
  - mysql-libs=8.3.0=h0e80b4a_5
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert=7.16.4=hd8ed1ab_1
  - nbconvert-core=7.16.4=pyhd8ed1ab_1
  - nbconvert-pandoc=7.16.4=hd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.5=h7bae524_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.9.1=h40ed0f5_0
  - networkx=3.4.2=pyh267e887_2
  - nose=1.3.7=py_1006
  - notebook=7.2.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - nspr=4.36=h5833ebf_0
  - nss=3.106=h6f44f80_0
  - numcodecs=0.14.0=py311hca32420_0
  - numpy=1.26.4=py311h7125741_0
  - numpydoc=1.8.0=pyhd8ed1ab_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - opencv=4.9.0=py311h24019a2_5
  - openh264=2.4.0=h965bd2d_0
  - openjpeg=2.5.2=h9f1df11_0
  - openssl=3.4.0=h39f12f2_0
  - opt_einsum=3.4.0=pyhd8ed1ab_0
  - overrides=7.7.0=pyhd8ed1ab_0
  - p11-kit=0.24.1=h29577a5_0
  - packaging=24.2=pyhff2d567_1
  - pandas=2.2.3=py311h9cb3ce9_1
  - pandoc=3.5=hce30654_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - panel=1.5.4=pyhd8ed1ab_0
  - param=2.1.1=pyhff2d567_0
  - parso=0.8.4=pyhd8ed1ab_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pathspec=0.12.1=pyhd8ed1ab_0
  - pcre2=10.44=h297a79d_2
  - peakutils=1.3.5=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=11.0.0=py311h3894ae9_0
  - pims=0.7=pyhd8ed1ab_0
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.43.4=hebf3989_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_2
  - prometheus_client=0.21.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_0
  - propcache=0.2.0=py311h460d6c5_2
  - protobuf=4.24.4=py311h4d1eceb_0
  - psutil=6.1.0=py311hae2e1ce_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pugixml=1.14=h13dd4ca_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - py-opencv=4.9.0=py311hee96954_5
  - pyasn1=0.6.1=pyhd8ed1ab_1
  - pyasn1-modules=0.4.1=pyhd8ed1ab_0
  - pycodestyle=2.12.1=pyhd8ed1ab_0
  - pyconify=0.1.6=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pydocstyle=6.3.0=pyhd8ed1ab_0
  - pyflakes=3.2.0=pyhd8ed1ab_0
  - pygithub=2.5.0=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyjwt=2.10.0=pyhff2d567_0
  - pylint=3.3.1=pyhd8ed1ab_0
  - pylint-venv=3.0.4=pyhd8ed1ab_0
  - pyls-spyder=0.4.0=pyhd8ed1ab_0
  - pynacl=1.5.0=py311h460d6c5_4
  - pynwb=2.8.2=pyh2e8e312_0
  - pyobjc-core=10.3.1=py311h09e6bbd_1
  - pyobjc-framework-cocoa=10.3.1=py311h09e6bbd_1
  - pyobjc-framework-coreservices=10.3.1=py311h460d6c5_1
  - pyobjc-framework-fsevents=10.3.1=py311h267d04e_1
  - pyopenssl=24.2.1=pyhd8ed1ab_2
  - pyparsing=3.2.0=pyhd8ed1ab_1
  - pyqt=5.15.9=py311hc49b008_5
  - pyqt5-sip=12.12.2=py311ha891d26_5
  - pyqtgraph=0.13.7=pyhd8ed1ab_0
  - pyqtwebengine=5.15.9=py311h14ede98_5
  - pysimplegui=4.60.5=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.10=hc51fdd5_3_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-flatbuffers=24.3.25=pyh59ac667_0
  - python-gssapi=1.9.0=py311heacfbe3_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-lsp-black=2.0.0=pyhd8ed1ab_0
  - python-lsp-jsonrpc=1.1.2=pyhd8ed1ab_0
  - python-lsp-server=1.12.0=pyhd8ed1ab_0
  - python-lsp-server-base=1.12.0=pyhd8ed1ab_0
  - python-slugify=8.0.4=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python.app=1.4=py311hdc19893_4
  - python_abi=3.11=5_cp311
  - pytoolconfig=1.2.5=pyhd8ed1ab_0
  - pytz=2024.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyuca=1.2=py_1
  - pyviz_comms=3.0.3=pyhd8ed1ab_0
  - pywavelets=1.7.0=py311ha7f2236_2
  - pyxdg=0.28=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h460d6c5_1
  - pyzmq=26.2.0=py311h730b646_3
  - qdarkstyle=3.2.3=pyhd8ed1ab_0
  - qhull=2020.2=h420ef59_5
  - qstylizer=0.2.3=pyhd8ed1ab_0
  - qt-main=5.15.8=hcd44e0d_23
  - qt-webengine=5.15.8=h850e111_4
  - qtawesome=1.3.1=pyh9208f05_0
  - qtconsole=5.6.1=pyhd8ed1ab_0
  - qtconsole-base=5.6.1=pyha770c72_0
  - qtpy=2.4.2=pyhdecd6ff_0
  - re2=2023.09.01=h4cba328_1
  - readline=8.2=h92ec313_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.9.4=pyhd8ed1ab_0
  - rope=1.13.0=pyhd8ed1ab_0
  - rpds-py=0.21.0=py311h3ff9189_0
  - rsa=4.9=pyhd8ed1ab_0
  - rtree=1.3.0=py311hc46b6d3_2
  - ruamel.yaml=0.18.6=py311hae2e1ce_1
  - ruamel.yaml.clib=0.2.8=py311hae2e1ce_1
  - scikit-image=0.20.0=py311h4eec4a9_1
  - scikit-learn=1.5.2=py311h9e23f0f_1
  - scipy=1.14.1=py311hf1db568_1
  - send2trash=1.8.3=pyh31c8845_0
  - setuptools=75.5.0=pyhff2d567_0
  - sip=6.8.6=py311h3f08180_1
  - six=1.16.0=pyh6c4a22f_0
  - slicerator=1.1.0=pyhd8ed1ab_0
  - snappy=1.1.10=hd04f947_1
  - sniffio=1.3.1=pyhd8ed1ab_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sphinx=8.1.3=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_0
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_0
  - spyder=6.0.2=osx_pyhbfa140f_3
  - spyder-kernels=3.0.1=unix_pyh707e725_0
  - spyder-terminal=1.2.2=pyhd8ed1ab_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - superqt=0.6.7=pyh9208f05_0
  - svt-av1=1.8.0=h463b476_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2022.0.0=h0cbf7ec_0
  - tensorboard=2.15.2=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py311h544b224_2
  - tensorflow=2.15.0=cpu_py311h9b82b1a_2
  - tensorflow-base=2.15.0=cpu_py311he034567_2
  - tensorflow-estimator=2.15.0=cpu_py311hcceb7c1_2
  - termcolor=2.5.0=pyhd8ed1ab_0
  - terminado=0.18.1=pyh31c8845_0
  - text-unidecode=1.3=pyhd8ed1ab_1
  - textdistance=4.6.3=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - three-merge=0.1.1=pyh9f0ad1d_0
  - tifffile=2020.6.3=py_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.1.0=pyhff2d567_0
  - tomlkit=0.13.2=pyha770c72_0
  - toolz=1.0.0=pyhd8ed1ab_0
  - tornado=6.4.1=py311h460d6c5_1
  - tqdm=4.67.0=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20241003=pyhff2d567_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2024b=hc8b5060_0
  - uc-micro-py=1.0.3=pyhd8ed1ab_0
  - ujson=5.10.0=py311h3f08180_1
  - unicodedata2=15.1.0=py311hae2e1ce_1
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - watchdog=6.0.0=py311h917b07b_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=24.8.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - werkzeug=3.1.3=pyhff2d567_0
  - whatthepatch=1.0.6=pyhd8ed1ab_0
  - wheel=0.45.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.13=pyhd8ed1ab_0
  - wrapt=1.14.1=py311he2be06e_1
  - wurlitzer=3.1.1=pyhd8ed1ab_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.11=hd74edd7_1
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xyzservices=2024.9.0=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - yapf=0.40.1=pyhd8ed1ab_0
  - yarl=1.17.2=py311h917b07b_0
  - zarr=2.18.3=pyhd8ed1ab_0
  - zeromq=4.3.5=hc1bb282_7
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zstandard=0.23.0=py311ha60cc69_1
  - zstd=1.5.6=hb46c0d2_0
  - pip:
      - box-sdk-gen==1.9.0
      - docstring-parser==0.15
      - experiment-analysis==0.1.0
      - neo==0.13.4
      - quantities==0.16.1
      - requests-toolbelt==1.0.0
      - xarray==2024.11.0
      - xrscipy==2.1.0
prefix: /Users/lukerichards/miniforge3/envs/caiman
